# .gitleaks.toml
title = "gitleaks config"
[[rules]]
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "SSH RSA Private Key"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
tags = ["key", "SSH"]
